### ISSUE TITLE
property headerShown not work on android

### ISSUE THREAD

**Issue by raivieiraadriano92** [react-navigation/navigation-ex#131]
Hi guys, the headerShown property does not work on android. In iOS is perfect, however in android appears a white header.

"@react-navigation/core": "^5.0.0-alpha.15",
"@react-navigation/native": "^5.0.0-alpha.12",
"@react-navigation/native-stack": "^5.0.0-alpha.1",

`import { NavigationNativeContainer } from '@react-navigation/native'
import { createNativeStackNavigator } from '@react-navigation/native-stack'

const Stack = createNativeStackNavigator()

<NavigationNativeContainer>
    <Stack.Navigator>
        <Stack.Screen
            name="ItineraryForm"
            component={ItineraryForm}
            options={{ headerShown: false }}
        />
    </Stack.Navigator>
</NavigationNativeContainer>`

![issue](https://user-images.githubusercontent.com/14861463/67113709-8fc37400-f1b0-11e9-975a-697b224facd1.png)

**Comment by developerreadme** [comment]
I have the same the same problem

**Comment by shem8** [comment]
I have the same problem

**Comment by jjg77** [comment]
headerShown doesn't work for me.  Instead I used "header: null"

**Comment by Rambatino** [comment]
Neither work for me on ios simulator.
