### ISSUE TITLE
Usage with Redux-Persist causes state to be overwritten

### ISSUE THREAD

**Issue by nextriot** [react-navigation/navigation-ex#138]
### Current Behavior

Using in combination with Redux-Persist, upon app being reloaded Redux-Persist's actions are fired, but then reloaded and any persisted state is overwritten. When I remove React Navigation the code acts as expected.

### Expected Behavior

The state should be persisted and the app should not be loaded twice.

### How to reproduce

Here is a link to a repo I created with the minimum required code to reproduce the error: https://expo.io/@kanguru/rn-nav-redux-persist
And here is the Githu repo for the project: https://github.com/nextriot/React-Navigation-5-Redux-Persist

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 
| @react-navigation/core | ^5.0.0-alpha.17
| @react-navigation/native | ^5.0.0-alpha.13
| @react-navigation/stack | ^5.0.0-alpha.29
| react-native     | 0.59.8
| expo             | 35.0.0
| node             | 10.16.0
| npm or yarn      | 1.10.1

**Comment by satya164** [comment]
Can you give some more details about what actually happens? Your example doesn't have anything to change redux state so can't tell what I should be looking at. Can you share a video?

**Comment by nextriot** [comment]
I've added `redux-logger` to the app, if you look at the logs in a browser you can see the redux-persist actions fire on load. However, if you uncomment the `withNavigator` component in `src/index.tsx` and comment out `withoutNavigator` you'll notice the actions trigger then re-trigger and the state is empty.

I've updated the Expo project and repo for clarity, I've also added a button to navigate from the `withNavigator` component which should satisfy the action request. 

Also, here's a gif of the issue for completeness. Let me know if there's anything else.


![img](https://media.giphy.com/media/fYI2wp9gBFTTJpnYsk/giphy.gif)

**Comment by satya164** [comment]
So what's happening is: in Redux devtools, "Autoselect instances" is selected. How this feature works is that it shows the devtools for the instance which dispatched the last action.

React Navigation also integrates with this devtools.

So, first the actions and state from redux-persist are dispatched and they are shown, and then when React Navigation renders, its state is initialized, so the devtools is switching to React Navigation's actions. Only thing that's changing is what's displayed. No state is overwritten. You can click on "Autoselect instances" and switch to the redux logs and they are still there.

**Comment by nextriot** [comment]
Thank you for enlightening me @satya164! That was indeed what was happening. Apologies for the premature reporting. V5 has been fantastic! Looking forward to the release.
