### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by keshavkaul** [react-navigation/navigation-ex#140]
### Current Behavior

1. Cocoa Pods fails to find tvos supported dependent libraries:
react-native-reanimated
react-native-masked-view
2. react-native-screens has a compile-time issue that I have logged in this issue when using stack navigator.
https://github.com/kmagiera/react-native-screens/issues/198

### Expected Behavior

tvos support should be seamless

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | next
| react-native     | 0.60.x
| expo             |
| node             | 10.x
| npm or yarn      | yarn 1.7

**Comment by satya164** [comment]
Please open issues regarding tvos support in the relevant libraries. We don't have bandwidth to work on it.

**Comment by keshavkaul** [comment]
Sure will do, I thought I'd create an issue here that will track tvos support status

**Comment by keshavkaul** [comment]
Update, `react-native-reanimated` supports tvos via podspec in version [1.4.0](https://github.com/kmagiera/react-native-reanimated/releases/tag/1.4.0)
