### ISSUE TITLE
[Android] Tab bar renders above keyboard

### ISSUE THREAD

**Issue by nhuesmann** [react-navigation/navigation-ex#141]
### Current Behavior

On Android, when the keyboard is shown, the bottom tab bar rises above the keyboard.

![gif](https://media.giphy.com/media/TfX4DjPNVXqQXWwRBw/giphy.gif)

### Expected Behavior

- The bottom tab bar should not move or animate
- I am currently using React Navigation 3 and this is not an issue
- I have also added the option `keyboardHidesTabBar: true` in the bottom tab bar navigator configuration, however that yields a janky animation.

### How to reproduce

Snack link: https://snack.expo.io/@nhuesmann/joyous-milkshake

### Your Environment

From `package.json`
```
"@react-native-community/masked-view": "^0.1.1",
"@react-navigation/bottom-tabs": "^5.0.0-alpha.15",
"@react-navigation/core": "^5.0.0-alpha.17",
"@react-navigation/native": "^5.0.0-alpha.13",
"@react-navigation/stack": "^5.0.0-alpha.29",
"expo": "^35.0.0",
"react": "16.8.3",
"react-dom": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"react-native-gesture-handler": "~1.3.0",
"react-native-reanimated": "~1.2.0",
"react-native-safe-area-context": "~0.3.6",
"react-native-screens": "~1.0.0-alpha.23",
"react-native-web": "^0.11.7"
```
**Other**
node: `v10.13.0`
yarn: `1.19.1`

### Related issues
- https://github.com/react-navigation/react-navigation/issues/1464
- https://github.com/react-navigation/tabs/issues/16
- https://github.com/callstack/react-native-paper/pull/680

**Comment by satya164** [comment]
That's how the keyboard on Android works based on what you have in your `AndroidManifest.xml` for `android:windowSoftInputMode`. By default it's `adjustResize` (I think) and when the keyboard is shown, the whole app's window resizes, which means that the navigators also need to resize because their parent resized, making the tab bar move up.

Not sure how it works for you in v3, but React Navigation's code has no control over if the screen is going to resize or not. So you'll need to tweak your app's config not to resize the screen if you don't want this behaviour.

The `keyboardHidesTabBar` option changes bottom margin on keyboard show/hide, so content will jump if the content isn't anchored to start of the screen. You can improve it by passing `style: { position: 'absolute' }` to the `tabBarOptions`.

**Comment by nhuesmann** [comment]
@satya164 Thank you for your response. I've seen solutions that involve changing the `AndroidManifest.xml`, however I'm working with an Expo project and don't want to detach.

I tried adding `style: { position: 'absolute' }` to `tabBarOptions` and it did not resolve the issue.
This config still results in the bottom tab bar animating when keyboard is shown or hidden:
```
tabBarOptions={{
  keyboardHidesTabBar: true,
  style: {
    position: 'absolute',
  },
}}
```
This config still results in the bottom tab bar still rendering above the keyboard:
```
tabBarOptions={{
  keyboardHidesTabBar: false,
  style: {
    position: 'absolute',
  },
}}
```

Is `{ position: 'absolute' }` expected to resolve this issue? It didn't work for me at all.

**Comment by nhuesmann** [comment]
@brentvatne any thoughts here? I know you've been heavily involved in commenting on related GH issues regarding tab bar and keyboard interaction on Android.

**Comment by nhuesmann** [comment]
I tried using `@react-navigation/material-bottom-tabs`, and though that fixes the bottom tab bar issue (it hides properly without jarring animations), changing between tabs causes the entire screen to flicker. There's a [GH issue](https://github.com/react-navigation/material-bottom-tabs/issues/19) for this problem.

@satya164 @brentvatne I haven't found a solution using the next version of `react-navigation` that provides a user experience free of jarring animations or unexpected behavior. It currently feels like I have to choose between having a bottom tab bar with a distracting animation when the keyboard visibility changes (`bottom-tabs`), or having a bottom tab bar that stays put but creates a full screen flash whenever the user changes tabs (`material-bottom-tabs`).

I am just wondering if someone could direct me toward a solution where these issues aren't present. Thanks in advance.

**Comment by brentvatne** [comment]
`keyboardHidesTabBar: true` isn't ideal but it's the best we can do right now with what is exposed by react-native's keyboard api, which if i understand correctly is limited by the related android apis. it seems that we can't know that the keyboard will appear before it does, and so we have to animate after the keyboard is already visible.

**Comment by nhuesmann** [comment]
@brentvatne thanks for the reply—after I posted I began to realize that the difference between `keyboardWillShow` on iOS and `keyboardDidShow` on Android is one of the main issues for this undesired behavior. I now understand this to be a limitation caused by React Native itself. One potential fix I can think of is having the bottom tab bar respond to input focus/blur rather than keyboard show/hide, which would obviously take hooking up every TextInput component. I wonder if it's something worth exploring.

Regarding `@react-navigation/material-bottom-tabs`, it's the closest i've found to a working solution, however like I mentioned, switching between tabs causes a flickering animation. Also, I just realized that `react-native-screens` is causing a flicker _every time_ I navigate within a stack navigator (Android only). Based on this, and based on the few issues I've been discussing, would you recommend I open a new issue that's more of a discussion of the current state of `react-navigation` on Android? I wonder if this could be helpful as somewhat of a catch-all for navigation issues on Android, since a lot of people are still running into these issues, and also because it involves several libraries (`react-navigation`, `react-native-paper`, `react-native-screens`, and I guess `expo` as well). Let me know what you think. I just would love to avoid having this GH issue disappear only to have another one crop up tomorrow regarding the same challenges.

**Comment by brentvatne** [comment]
i'm not familiar with what `@react-navigation/material-bottom-tabs` does differently, perhaps you could investigate.

react-native-screens is still in alpha unfortunately, it's taking a while to work through these issues. you might want to opt out of using it if it's causing issues for your app.

**Comment by MonchiLin** [comment]
any progress?
