### ISSUE TITLE
resetOnBlur isn't implemented in bottomTabNavigator

### ISSUE THREAD

**Issue by melodydrewvr** [react-navigation/navigation-ex#142]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report.

---

### Current Behavior

- What code are you running and what is happening?

When I try to use the resetOnBlur prop on the bottomTabNavigator, nothing happens (and TypeScript tells me the prop doesn't exist).

<img width="754" alt="Screenshot 2019-10-26 at 11 57 44" src="https://user-images.githubusercontent.com/54799983/67618473-07645500-f7e8-11e9-958c-c3009fce4679.png">

### Expected Behavior

- What do you expect should be happening?

resetOnBlur prop should exist and should be resetting the tab stack when pressed.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

Create a bottomTabNavigator and add a stack as one of its screen. Add the resetOnBlur prop to the navigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.17
| react-navigation/bottom-tabs | 5.0.0-alpha.14
| react-native     | 0.61.2
| expo             | n/a
| node             | v12.9.1
| npm or yarn      | 6.10.2

--------

I've gone through the code and I can clearly see this prop hasn't been implemented yet, but I thought I'd raise this issue as it is included in the documentation.

**Comment by satya164** [comment]
Can you describe your usecase for `resetOnBlur`?

**Comment by melodydrewvr** [comment]
In our app, we'd like to be able to select a tab and have it display the stack from its initial screen rather than where it's been navigated to. So, for example, if you're on the third tab and drill down through a few screens, when you navigate to another tab and then back to tab three it should be back to the first screen rather than where you'd previously navigated to.

**Comment by satya164** [comment]
You can use the `unmountInactiveScreens` option in the latest version of bottom tabs. If it doesn't satisfy your use case, you should be able to do something like this inside the screen which renders the stack:

```js
React.useEffect(
  () =>
    navigation.addListener('tabPress', () => {
      if (navigation.isFocused() && route.state) {
        navigation.dispatch({
          ...StackActions.popToTop(),
          target: route.state.key,
        });
      }
    }),
  [navigation, route.state]
);
```

**Comment by melodydrewvr** [comment]
Thanks @satya164 for the response, I'll give that a try.

However, if this prop isn't going to be supported it might help to remove it from the API documentation as it's what lead me to believe it was a missing feature.

https://reactnavigation.org/docs/en/next/bottom-tab-navigator.html

Thanks again!
