### ISSUE TITLE
Custom TabBarComponent with Material Top Tabs

### ISSUE THREAD

**Issue by artyorsh** [react-navigation/navigation-ex#144]
### Current Behavior

Currently, when using `createMaterialTopTabNavigator` with custom `tabBarComponent`, the library crashes when attempting to import `react-native-tab-view`.

### Expected Behavior

I guess, it should not fail when using custom `tabBarComponent`. At least, if the swiping behavior is provided by this library, wouldn't it be better to include this library as `@react-navigation/material-top-tabs` dependency? 

### How to reproduce

```jsx
const TopTab = createMaterialTopTabNavigator<TodoTabsNavigatorParams>();

const TodoTabsNavigator = (): React.ReactElement => (
  <TopTab.Navigator tabBarComponent={TodoScreen}>
    <TopTab.Screen name={AppRoute.TODO_IN_PROGRESS} component={TodoInProgressScreen}/>
    <TopTab.Screen name={AppRoute.TODO_DONE} component={TodoDoneScreen}/>
  </TopTab.Navigator>
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | The latest versions of 5.0.0-alpha.*
| react-native     | 0.61.2
| expo             | - 
| node             | 10.16.3
| npm or yarn      |

**Comment by satya164** [comment]
Can you provide full code please?

**Comment by artyorsh** [comment]
Sure. Can I do this simply sharing links to the repo files?
- [TabNavigator](https://github.com/artyorsh/react-navigation-ex-demo/blob/complete-exmaples/src/navigation/todo.navigator.tsx)
- [TabBarComponent](https://github.com/artyorsh/react-navigation-ex-demo/blob/complete-exmaples/src/scenes/todo/todo.component.tsx)
- [package.json](https://github.com/artyorsh/react-navigation-ex-demo/blob/complete-exmaples/package.json)

I had to install react-native-tab-view (installed as devDependency) to make this work

**Comment by satya164** [comment]
You need to install `react-native-tab-view` as a dep. It's a peer dependency (https://github.com/react-navigation/navigation-ex/blob/aa401302666e57a0975d1392d2dac0fbdce8e9c9/packages/material-top-tabs/package.json#L57) and is also mentioned in the installation instructions https://reactnavigation.org/docs/en/next/material-top-tab-navigator.html

**Comment by artyorsh** [comment]
@satya164 I mean this feels confusing when you're using custom `tabBarComponent`

**Comment by satya164** [comment]
@artyorsh maybe you can describe a bit more what's the issue about what's wrong with custom tab bar component? can you provide a stack trace for the crash? `react-native-tab-view` needs to be installed whether or not you use a custom tab bar.
