### ISSUE TITLE
isFirstRouteInParent() has been removed in the last alpha?

### ISSUE THREAD

**Issue by ivnnv** [react-navigation/navigation-ex#152]
Hi,

I have been using `navigation.isFirstRouteInParent()`to have a custom component inside the navigator that will render a back icon or nothing whether or not the user is in the first (tab landing screen) or child screen.

Why this utility function has been it removed? And how can we now detect user is in the very first screen of a stack navigator apart of "canGoBack"?
Because canGoBack doesn't work for this use case when the user change the tab.

**Comment by ivnnv** [comment]
Ok I have read the comment in the commit that dropped the method and I dont really think (and seems the author neither) its the best approach to use a "dangerously" approach to check if we are in the first route, the isFirstRouteInParent method its really self explanatory and yes its very specific to the stack navigator so, why dont just keep it on it?

```
It's also possible to check if a route is the first by doing 
`navigation.dangerouslyGetState().routes[0].key === route.key`.
```

Im pretty sure I wont be the only one to miss this method when v5 goes public, I find it really useful.

**Comment by satya164** [comment]
Your use case is very specific and there's a way to do what you want. We can't have methods for every use case.

> use a "dangerously" approach to check if we are in the first route

You can extract it out to a hook:

```
function useIsFirstRoute = () => {
  const navigation = useNavigation();
  const route = useRoute();

  return navigation.dangerouslyGetState().routes[0].key === route.key
}
```

> yes its very specific to the stack navigator so, why dont just keep it on it

Because every extra feature increases maintenance cost. This simple method needed special handling for caching which was easy to break. It needs code in the core while being useless for all navigators except stack.

**Comment by ivnnv** [comment]
Plus the proposed alternative doesnt actually work, this is my setup:

AppNavigator.js
```
...
const BottomNav = createBottomTabNavigator();
...
```

BottomNav has 5 navigators, the first one is SearchNavigator

SearchNavigator.js:
```
...
const Stack = createStackNavigator();

const screenOptions = {
  title: "search.title",
  headerLeft: () => <LeftNavButton />, // just a functional component with few logic
  headerTitle: props => <NavTitle {...props} />,
  headerRight: () => <RightNavButton />,
  cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
};

const SearchNavigator = () => (
  <Stack.Navigator initialRouteName="SearchStep1" screenOptions={screenOptions}>
    <Stack.Screen name="SearchStep1" component={SearchStep1} />
    <Stack.Screen name="SearchStep2" component={SearchStep2} />
    <Stack.Screen name="SearchStep3" component={SearchStep3} />
    <Stack.Screen name="SearchResults" component={SearchResults} options={{ title: "search_results.title" }} />
    <Stack.Screen name="Tester" component={Tester} />
  </Stack.Navigator>
);
```

LeftNavButton.js:
```
...
const LeftNavButton = ({ logoIcon, buttonText }) => {
  const navigation = useNavigation();
  const route = useRoute();
  const isFirstRouteInParent = navigation.dangerouslyGetState().routes[0].key === route.key; // doesnt work because route.key always returns SearchStep1.key, even if we are already on SearchScreen2

  return (
    ...
  )
}
```

**Comment by satya164** [comment]
```js
headerLeft: props => <LeftNavButton {...props} />
```

```js
const LeftNavButton = ({ canGoBack }) => {
  if (canGoBack) {
     // There are screens before this
  }

  // We're on first screen
}
```

**Comment by ivnnv** [comment]
Just tested it passing the props and that totally did the trick.
Thanks @satya164 !
