### ISSUE TITLE
Bottom Tabs alpha > .14 missing tab buttons

### ISSUE THREAD

**Issue by joshuakelly** [react-navigation/navigation-ex#160]
### Current Behavior

- Updated to ^5.0.0-alpha.18 and the tab bar ends up blank, reinstalling alpha.14 brings the tabs back and works as normal.

### Expected Behavior

- Tab bar buttons are displayed

### How to reproduce

- Latest alpha of all v5 dependencies and adding the bottom tab navigator will hide the buttons whne using alpha.18 of bottom-tabs.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v5
| react-native     | v61.3
| node             | v12.13
| npm or yarn      | yarn

**Comment by JoeLeung32** [comment]
![Screenshot 2019-11-05 at 10 06 17 AM](https://user-images.githubusercontent.com/37429278/68172832-f2d84780-ffb3-11e9-9eb6-b01a0ac27496.png)
```
        <NavigationNativeContainer>
            <Tab.Navigator>
                <Tab.Screen name="Feed" component={HomeScreen} />
                <Tab.Screen name="Article" component={HomeScreen} />
            </Tab.Navigator>
        </NavigationNativeContainer>
```

**Comment by satya164** [comment]
Please update to the latest version.

**Comment by joshuakelly** [comment]
Issue is fixed, cheers.
