### ISSUE TITLE
v5 - tabBarVisible is not an option

### ISSUE THREAD

**Issue by rolandoldengarm** [react-navigation/navigation-ex#181]
### Current Behavior

Trying to set tabBarVisible to false on a screen's options. Typescript doesn't allow me to set it:
![image](https://user-images.githubusercontent.com/14539000/69221602-8e84cd00-0bdc-11ea-9cb9-15da91ad488e.png)

Also tried to set it in the screen itself, no luck:
```
const navigation = useNavigation();
navigation.setOptions({tabBarVisible: false});
```
Looking at the documentation [here](https://reactnavigation.org/docs/en/next/bottom-tab-navigator.html).

### Expected Behavior
I'm able to hide the tab bar on certain screens.

### How to reproduce
See code above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.22

**Comment by satya164** [comment]
You haven't posted any repro, but looks like you're using `@react-navigation/material-bottom-tabs` (`createMaterialBottomTabNavigator`) which is just a wrapper over https://callstack.github.io/react-native-paper/bottom-navigation.html. It doesn't support hiding the tab bar, so you'll need to open an issue in the [`react-native-paper` repo](https://github.com/callstack/react-native-paper) if you want it.

The documentation you have linked to is for `@react-navigation/bottom-tabs` (`createBottomTabNavigator`) and `tabBarVisible` is available there.
