### ISSUE TITLE
headerForceInset prop missing in 5.x

### ISSUE THREAD

**Issue by davidsamacoits** [react-navigation/navigation-ex#183]
### Current Behavior

Using the latest version, `headerForceInset` is not available anymore. You can't control your safe areas in headers, creating UI glitches like this when you use modals :

<img width="440" alt="Screen Shot 2019-11-23 at 5 33 09 PM" src="https://user-images.githubusercontent.com/27018364/69486210-603f0180-0e17-11ea-9696-6f7dd219f334.png">

### Expected Behavior

`headerForceInset` should allow you to specify and control safe area.
Link to the missing prop in v4.x https://reactnavigation.org/docs/en/stack-navigator.html#headerforceinset

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.23
| react-native     | 0.61.4
| node             | 10.16.3
| npm or yarn      | 1.15.2

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/stack-navigator.html#safeareainsets

**Comment by davidsamacoits** [comment]
This issue shouldn't be closed! `safeAreaInsets` is used to control SafeAreas for the *ENTIRE* screen. In v4.x you could specify the behaviour of SafeAreas for the header only (as mentioned here https://reactnavigation.org/docs/en/stack-navigator.html#headerforceinset).
Therefor this option is missing in v5.x so this issue should be reopen.

**Comment by satya164** [comment]
Did you actually test it?

There's no difference. Safe are insets are only used in the header.

**Comment by davidsamacoits** [comment]
Actually I did and couldn't get the expected behaviour. But I gave it another try this morning changing the my router was built and it works! My bad :)
However, for users (like me) used to the v4.x version, a quick note in the doc would be appreciated regarding how this `safeAreaInsets` applies and how there's no longer a difference between safeAreaInsets and headerForceInset.
