### ISSUE TITLE
UseIsFocused wrong value after resetRoot()

### ISSUE THREAD

**Issue by Titozzz** [react-navigation/navigation-ex#185]
### Current Behavior

https://github.com/Titozzz/rn5-issues/tree/bug-focus

Running this code, when moving from tab2 to stack2 using resetRoot(), useIsFocused() has the wrong value for tab1 and stack2.
I've added logs to the demo above 🚀!

### Expected Behavior

useIsFocused() should stay in sync with the navigation state
Thanks 😄

**Comment by meftunca** [comment]
> TypeError: navigation.resetRoot is not a function
I get this error. What do you think might be the cause of this problem? I get this error when using "DeepLinking".
