### ISSUE TITLE
Stale state data calling a function from a header button with useEffect

### ISSUE THREAD

**Issue by kbrandwijk** [react-navigation/navigation-ex#194]
### Current Behavior

1. In my function component, I use `navigation.setOptions` to set headerRight to a `TouchableOpacity` using `useEffect`. The `onPress` points to a local function in my component.
2. I use the `useState` hook to keep track of some state information, that changes due to things happening on the screen (not too relevant how, it's just normal `useState` usage)
3. Whenever I press the button in the header, the function that is called accesses this state variable, and that variable does not return the most recent value, in other words, it has the value it had when `navigation.setOptions` was called.
4. I confirmed this by adding my state variable to the `useEffect` variables array, effectively re-calling `setOptions` every time it changes. Now, when the function is called, the state variable does have the latest value.

If I use `useFocusEffect` instead of `useEffect`, it works fine: I'm unsure why `useEffect` doesn't work, my reasoning was: I don't need `useFocusEffect`, because I don't have to set these navigationOptions every single time the screen focuses, just once, when it's created.

I'm not 100% comfortable and intimate yet with that whole new hooks lifecycle stuff, but hopefully this makes sense to someone. 

### Expected Behavior

I would expect the function called by the header button to have access to the _current_ context, instead of what seems like a 'snapshot' of when it was set.

### How to reproduce

https://snack.expo.io/@agartha/trusting-chocolates-2 with `useEffect` (does not work)
https://snack.expo.io/@agartha/trusting-chocolates with `useFocusEffect` (works)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.24 (core), .16 (native), .37 (stack)
| react-native     | 0.61.5
| expo             | -
| node             | 11.12.0
| yarn      | 1.15.2

**Comment by kbrandwijk** [comment]
Interesting thing about isolating issues in Snacks is how they have a habit of not occuring. https://snack.expo.io/@agartha/trusting-chocolates is a very minimal example, where the issue does _not_ occur. I see if I can find out what's different between this and the real project, otherwise I'll close this issue.

**Comment by kbrandwijk** [comment]
Also, thinking about it a bit more, I actually have cases where I _need_ to use `useEffect` instead of `useFocusEffect`, because I want the header to respond to changes on the screen. Because of the issue above, this means that whenever I use `useEffect`, I need to make sure that I have every single state variable that I need in any of the functions called from the header in the variables array for `useEffect`, to prevent the 'stale data' issue from happening.

**Comment by satya164** [comment]
You're passing empty dependency array to `useEffect`. You need to pass correct dependencies as mentioned in React docs https://reactjs.org/docs/hooks-effect.html

**Comment by kbrandwijk** [comment]
Well, that's a bit quick to close. I should pass dependencies to `useEffect` if I want something to happen. In this case, I have already set the navigationOptions once, so I really don't want anything to happen, right? The header stays the same, the button stays the same, the function it calls also stays the same.

**Comment by satya164** [comment]
You want the state update to be reflected in the option you set, so you need to re-run the effect. Empty dependency array is almost always a bug. You should use https://www.npmjs.com/package/eslint-plugin-react-hooks#installation which takes care of passing correct dependency array.

`useFocusEffect` will run every render. For dependency array with `useFocusEffect`, you need to use `React.useCallback` as mentioned in docs https://reactnavigation.org/docs/en/next/use-focus-effect.html
