### ISSUE TITLE
navigation.navigate does not reset route params

### ISSUE THREAD

**Issue by kbrandwijk** [react-navigation/navigation-ex#195]
---

### Current Behavior

I have a screen that's part of a bottomTabNavigator. I have two ways of navigating to this screen:

- Tapping somewhere on one of the screens calls `navigation.navigate('MyScreen', { myParam: 'value' })`
- Tapping on the button in the bottom tabbar

Now as soon as I've navigated to the screen once _with_ a route parameter, I have no way of resetting this param. The next time I use the tabbar button, the screen will still have that value in `route.params.myParam`. Even using `unmountInactiveScreens` to completely get rid of the screen doesn't clear the route param.

To isolate the issue from the tabbar, I also added a direct call to `navigation.navigate('MyScreen')`, and noticed the route param also not reset.

### Expected Behavior

Subsequently navigating to a screen without specifying any route params should clear the previous ones.

### How to reproduce

https://snack.expo.io/@agartha/route-params

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.24 (core), .16 (native), .37 (stack)
| react-native     | 0.61.5
| expo             | -
| node             | 11.12.0
| yarn      | 1.15.2

**Comment by satya164** [comment]
This is expected behaviour. Params are always merged. If you want to reset a param, you can explicitly set it to `undefined`:

```js
navigation.navigate('MyScreen', { myParam: undefined })
```

**Comment by kbrandwijk** [comment]
How can I make the tabbar do so?

**Comment by satya164** [comment]
You can add a listener on `tabPress` where you can reset the param with `setParams` inside your screen.

**Comment by kbrandwijk** [comment]
Although that would work, it totally turns the chain of responsibility of the components upside down. The screen is just responsible for displaying data, using whatever params I pass in. It shouldn't need to know that it lives inside a tab navigator, and that it needs to do something when the tab is pressed. Surely, this sounds like the responsibility of the tab navigator. Shouldn't there be some way to specify default route params on a `Tab.Screen` or something similar? Or disable the merge behavior?

**Comment by satya164** [comment]
The helpers available on the `navigation` prop depend highly on which navigator its inside of, methods such as `jumpTo`, which options can be set with `setOptions` etc. Unless you only use the common methods such as `navigate`, the screen is aware of the navigator most of the time. If you try to make the screens not aware of the navigator, it'll just limit the functionality.

Anyway, `tabPress` isn't probably the correct way if your use case is "reset the params when this screen comes into focus again". It'll be better to use `useFocusEffect` to reset the params.

It's important to note that Params are not props. They have the characteristic of both props and state, which makes managing params the responsibility of the screen.
