### ISSUE TITLE
Authentication flows screen transition

### ISSUE THREAD

**Issue by kockok** [react-navigation/navigation-ex#197]
I was following the guide [here](https://reactnavigation.org/docs/en/next/auth-flow.html).

```
return (
  <Stack.Navigator>
    {isLoading ? (
      // We haven't finished checking for the token yet
      <Stack.Screen name="Splash" component={SplashScreen} />
    ) : userToken === null ? (
      // No token found, user isn't signed in
      <Stack.Screen name="SignIn">
        {() => <SignInScreen setUserToken={setUserToken} />}
      </Stack.Screen>
    ) : (
      // User is signed in
      <Stack.Screen name="Home" component={HomeScreen} />
    )}
  </Stack.Navigator>
);
```

It's good to see a screen transition from login to home.
However, when a user is logged in, there's an automatic transition from login screen to home screen every time the user reopens the app.

So, I wonder how to  skip such a transition when the user is already logged in albeit keeping the transition from the login screen the first time.

**Comment by kockok** [comment]
![myVideo](https://user-images.githubusercontent.com/232541/70417900-333c5100-1a9d-11ea-882d-2eed6729e158.gif)

**Comment by satya164** [comment]
There's a mistake in the docs. `setIsLoading(false)` should be done after `setUserToken(token)`, not before. But the proper approach is to use `useReducer` to set them both together. I've updated the docs to use it.

**Comment by kockok** [comment]
> There's a mistake in the docs. `setIsLoading(false)` should be done after `setUserToken(token)`, not before. But the proper approach is to use `useReducer` to set them both together. I've updated the docs to use it.

Thanks for the update, and yet the logged in state is not kept when the app is refreshed.

**Comment by satya164** [comment]
That's for you to persist whatever token you have to async storage after login.

**Comment by kockok** [comment]
> That's for you to persist whatever token you have to async storage after login.

There's still a transition effect when the user is logged in.

My question is that when a logged in user reopens the app, how to skip the transition effect from the login screen to the logged in screen?
