### ISSUE TITLE
is getActiveChildNavigationOptions still supported if not please support it 

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/navigation-ex#220]
The current version of react-navigation i.e v4 has a function getActiveChildNavigationOptions, which is used to set the screen options of parent navigator from child navigators screen. It is very handy to set screen options from nested navigators. (note in v1 by default screen options where merged from child navigators with all parent navigators hence there was no use of this getActiveChildNavigationOptions)
1. Will this API be still supported in v5 or will there be any changes?
2. Without this API, we cannot make use of some nesting patterns.

**Comment by satya164** [comment]
It won't be supported because it's impossible to support with a dynamic API. You'll need to change your approach to achieve the behaviour you want https://reactnavigation.org/docs/en/next/screen-options-resolution.html#setting-parent-screen-options-based-on-child-navigators-state

**Comment by ravirajn22** [comment]
I have a bottom tab navigator where each tab screen is a stack navigator, I use stack navigator because I want to control app bar. Now this tab screen i.e the stack navigator contains a top tab navigator.

```
BottomTabNavigator
       Screen -> StackNavigator containing the app bar
                                     Screen -> TopTabNavigator
                                                                 Screen -> Plain Component from where I need to control app bar options of ancestors app bar, i.e StackNavigator 1 level above
```

> You can imagine the structure like an app with bottom and top tab both simultaneously visible and to control the app bar from the screens of top tab.

You can see sample image in this link https://github.com/react-navigation/react-navigation/issues/5061

Previously I used to use getActiveChildNavigationOptions in the TopTabNavigator navigationOptions. The navigationOptions will be merged from the child screen, hence the StackNavigator navigationOptions gets updated properly. 

Now that getActiveChildNavigationOptions is not supported, can you give me some ideas on how to proceed with this structure in v5. 

Changing the structure of navigators is not possible because this pattern of structure is used by many common apps and best suits our app.  Please guide me.
