### ISSUE TITLE
gestureEnabled in createNativeStackNavigator has no effect

### ISSUE THREAD

**Issue by arberK** [react-navigation/navigation-ex#228]
The option 'gestureEnabled' under StackNavigator seems not to work.  I want to disable closing of the modal screen by swiping down in the cases such {presenation = 'modal'}.

**Comment by Hirbod** [comment]
It works, but only for non-modal.

**Comment by bisak** [comment]
I have the exact same issue with the default `stackPresentation` which is not modal.
