### ISSUE TITLE
StackNavigator bug after navigating to another navigator inside a BottomTabNavigator

### ISSUE THREAD

**Issue by ctopher7** [react-navigation/navigation-ex#253]
I have 2 navigator inside BottomTabNavigator. The first navigator is a StackNavigator and the second one is MaterialTopTabNavigator.

### Current Behavior
When the StackNavigator first mounted, it behaves correctly, however after I navigate to the MaterialTopTabNavigator and go back to the StackNavigator, the StackNavigator can't navigate to another screen

![bug2](https://user-images.githubusercontent.com/43805090/71869125-7b559e80-3143-11ea-8e83-5b7135211311.gif)

### Expected Behavior
StackNavigator should be able to navigate to another screen even after navigating to MaterialTopTabNavigator

### Your Environment
```
    "@react-native-community/masked-view": "^0.1.5",
    "@react-navigation/bottom-tabs": "^5.0.0-alpha.32",
    "@react-navigation/material-top-tabs": "^5.0.0-alpha.27",
    "@react-navigation/native": "^5.0.0-alpha.22",
    "@react-navigation/stack": "^5.0.0-alpha.54",
    "react-native": "0.61.5",
    "react-native-reanimated": "^1.4.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-safe-area-context": "^0.6.1",
    "react-native-tab-view": "^2.11.0"
```

**Comment by ctopher7** [comment]
i just add another stack navigator inside the bottom tab navigator, i navigate to another stack, and back to the initial stack (home stack), it can't navigate to another screen (like in the GIF)

**Comment by satya164** [comment]
Can you provide a repro?

**Comment by ctopher7** [comment]
@satya164 thank you for your reply, here is my code:

**Comment by ctopher7** [comment]
i could add a hack, which is adding unmountInactiveScreens=true on <Tab.Navigator>. But it will always remount when i go back to that tab

**Comment by ctopher7** [comment]
this issue only occur on Android

**Comment by satya164** [comment]
Can you provide a runnable repro on snack or GitHub repo please? Are using react-native-screens (`enableScreens()`)?

**Comment by ctopher7** [comment]
@satya164 hi, yes I used react-native-screens (enableScreens()) . After I disabled it, the problem solved. Sorry for the fuss. Thank you so much for your answer

**Comment by papigers** [comment]
This shouldn't be closed - it's still an issue - unless you're implying the issue should be opened on `react-native-screens`,

**Comment by satya164** [comment]
@papigers https://github.com/react-navigation/navigation-ex/issues/226
