### ISSUE TITLE
How to prevent AppBar  header to animate on view change on Android?

### ISSUE THREAD

**Issue by kopax** [react-navigation/navigation-ex#278]
**Current Behavior**

I am using `@react-navigation/stack@5.0.0-alpha.53` and I use the `TransitionPresets.SlideFromRightIOS`.

When the next view comes in, it also brings the `<AppBar />` header with animation, making it slide on top of the initial header.

Is there a way to prevent that glitch and disable animation on the `<AppBar />`?

**Expected Behavior**

I expect the AppBar to be fixed

**How to reproduce**

```jsx
import * as React from 'react';
import { createStackNavigator as createStackNavigatorDefault, TransitionPresets } from '@react-navigation/stack';
import Constants from 'expo-constants';
import { getStackConfig } from './utils';

export default function createStackNavigator(routes) {
  const REACT_PAPER_APPBAR_HEIGHT = 56;
  const Stack = createStackNavigatorDefault();
  // eslint-disable-next-line react/prop-types
  return ({ screenOptions }) => (
    <Stack.Navigator
      {...getStackConfig(routes)}
      screenOptions={{
        headerStyle: {
          height: Constants.statusBarHeight + REACT_PAPER_APPBAR_HEIGHT,
        },
        ...TransitionPresets.SlideFromRightIOS,
        ...screenOptions,
      }}
    >
      {routes.map((route) => (
        <Stack.Screen
          key={route.path}
          name={route.page}
          component={route.component}
          options={{ title: route.message }}
        />
      ))}
    </Stack.Navigator>
  );
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/stack         | 5.0.0-alpha.53
| expo                           | sdk36
| node                           | v13.5.0
| npm                     | 6.13.4

**Comment by satya164** [comment]
Can you create a repro on https://snack.expo.io and show a video of which animation you are talking about?

**Comment by kopax** [comment]
Hi @satya164, here is the snack  https://snack.expo.io/@kopax/android-issue

And this a small GIF (if it doesn't load on github, just open it in a new tab)

[![SmartSelect_20200122-225741_Video-Player.gif](https://s5.gifyu.com/images/SmartSelect_20200122-225741_Video-Player.gif)](https://gifyu.com/image/qstZ)

**Comment by satya164** [comment]
What exactly is the glitch? You screen is sliding in, so how would you expect the header to change to the header of the next screen?

If you want the same behavior as iOS, you can use `headerMode="float"`, but you'll need to apply some kind of animation to your header change because otherwise it'll be a sudden change and look ugly https://reactnavigation.org/docs/en/next/stack-navigator.html#headermode

Closing since there's no bug here.

**Comment by kopax** [comment]
> What exactly is the glitch? Your screen is sliding in, so how would you expect the header to change to the header of the next screen?

The header is not fixed, and that is less nice than the effect I have on iOS which looks well designed.

> If you want the same behavior as iOS, you can use headerMode="float", but you'll need to apply some kind of animation to your header change because otherwise it'll be a sudden change and look ugly https://reactnavigation.org/docs/en/next/stack-navigator.html#headermode


Appying `headerMode="float"` instead of `headerMode="screen"` does not change anything.

> Closing since there's no bug here.

So this is expected on Android and cannot be improved to fit all use cases?
