### ISSUE TITLE
Setting header (navigation bar) options from top tab nested in Stack

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/navigation-ex#280]
I have a configuration like,
```
<Stack>
    <StackScreen name='Home'  component={Home}  />
    <StackScreen name='Profile'  component={Profile}  />
    <StackScreen name='Settings'  component={Settings}  />
</Stack>
```

The `Home` component is again a TopTabNavigator, with two tab screens like,

```
<TopTab>
      <TabScreen name="Home1" component={Home1} />
      <TabScreen name="Home2" component={Home2} />
</TopTab>
```

<img width="286" alt="Screenshot 2020-01-22 at 9 45 59 PM" src="https://user-images.githubusercontent.com/10977864/72913780-a5be7300-3d63-11ea-835a-546acdcc5aaa.png">

So in my case header bar (navigation bar) is provided by the Stack navigator.
Since TopTab navigator is nested inside the Stack navigator there is no direct way
to control header options from inside the tab screen components like `Home1` and `Home2`.

I want different RightButton to be shown based on the currently selected tab and
onPress of these buttons should have access to the tab screen objects like
props, state, context etc.

How to achieve the above behaviour?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/screen-options-resolution.html#setting-parent-screen-options-based-on-child-navigators-state

**Comment by ravirajn22** [comment]
I have read the link provided already but how does it apply to my case, it might work for bottomTab navigator where you can add a StackNavigator for each tab screen, whereas in case of TopTab navigator when you add  a StackNavigator for each screen, the header bar (navigation bar) comes below the tabs.

**Comment by satya164** [comment]
> bottomTab navigator where you can add a StackNavigator for each tab screen

That's not what the code in the link does.

**Comment by ravirajn22** [comment]
> bottomTab navigator where you can add a StackNavigator for each tab screen

The second part of the doc where you talk about reorganising routes suggest that solution.

Besides, I don't know if I am getting the point, but according to the docs you suggest adding a function like 

```
function getRightComponent(route) {
     switch(getRouteName(route)) {
           case 'Home1': return AddButton;
           case 'Home2': return EditButton;
     }
}
```

And add this `getRightComponent()` to the options prop for the Home stackscreen, right? I understand this, but the buttons `AddButton` and `EditButton` should have access to the screen state i.e AddButton must have access to `Home1` tabscreen state likewise `EditButton` must have access to `Home2` tabscreen state. For that these buttons must be declared inside their respective screens.

The example you have given works for cases where the headerOptions does not require access to screens state,


```
// Just switch title string (Which does not depend on any screen variables like state, props etc)
function getHeaderTitle(routeName) {
  switch (routeName) {
    case 'Home1': return 'Home1';
    case 'Home2': return 'Home2';
}
```

Do you have any simple solution for this?

Thanks.

**Comment by satya164** [comment]
Lift your state up if you want to access it in a parent. You can't have child component updating parent and parent updating child in React. Data flow is unidirectional and from parent to child.

**Comment by ravirajn22** [comment]
Thanks, I will try alternate techniques. Still haven't got used to component based Navigation.
