### ISSUE TITLE
Cant find useNavigationState

### ISSUE THREAD

**Issue by lucasluca** [react-navigation/navigation-ex#282]
**Current Behavior**

- Im using react navigation v5 Aplha and i try to import the hook useNavigationState, but it could not find it
- Include a screenshot or video if it makes sense.

**Expected Behavior**

-
![image](https://user-images.githubusercontent.com/16627838/72990510-08008d80-3dcf-11ea-9e42-9da34bcbba0a.png)

**How to reproduce**

-just installed react navigation v5 dependencies and can not get useNavigationState

**Comment by karavaan** [comment]
Try to import from `@react-navigation/navigation` instead.

**Comment by lucasluca** [comment]
There is no useNavigationState export on native folder 
![image](https://user-images.githubusercontent.com/16627838/73037859-4168e580-3e2f-11ea-8201-768f7a221675.png)

**Comment by lucasluca** [comment]
![image](https://user-images.githubusercontent.com/16627838/73037906-665d5880-3e2f-11ea-89f3-e73679d737da.png)

**Comment by satya164** [comment]
Please upgrade your packages to latest `@next`
