### ISSUE TITLE
Passing params to nested navigators

### ISSUE THREAD

**Issue by thijs-qv** [react-navigation/navigation-ex#291]
**Current Behavior**

Params are not passed between nested navigators.

**Expected Behavior**

Access to the passed params via the route.params object.

**How to reproduce**

TabNavigator
**StackNavigator
****Screen A
****Screen B
**StackNavigator
****Screen C

When Navigating from screen A or B to C (or vice versa) with props.navigation.navigate('C', {myParam: myValue}), route.params is undefined on screen C. When navigating from A to B the params do get passed. Is there any way to access these props on screen C?

I have found these threads which I believe deal with the same issue:
[issue 4811](https://github.com/react-navigation/react-navigation/issues/4811)
[rfc 43](https://github.com/react-navigation/rfcs/issues/43)

How can I pass params from screen A to C?

If needed I will create an example project which shows the issue.

**Comment by satya164** [comment]
Please provide a full repro

**Comment by thijs-qv** [comment]
`import React from 'react';
import { View, Text, } from 'react-native';

import 'react-native-gesture-handler';
import { NavigationNativeContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createStackNavigator } from '@react-navigation/stack';


const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

function MyTabs() {
  return (
    <Tab.Navigator initialRouteName='Stack1'>
      <Tab.Screen name="Stack1" component={Stack1} />
      <Tab.Screen name="Stack2" component={Stack2} />
    </Tab.Navigator>
  );
}

function Stack1() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="ScreenA" component={Screen1} />
      <Stack.Screen name="ScreenB" component={Screen2} />
    </Stack.Navigator>
  );
}

function Stack2() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="ScreenC" component={Screen2} />
    </Stack.Navigator>
  );
}

function Screen1(props) {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text onPress={() => props.navigation.navigate('ScreenB', {myParam: 'myValue'})} style={{marginBottom: 32}}>navigate to screen B with params</Text>
      <Text onPress={() => props.navigation.navigate('Stack2', {myParam: 'myValue'})}>navigate to screen C with params</Text>
    </View>
  );
}

function Screen2(props) {
  console.log(props)
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>myParam: {props?.route?.params?.myParam || 'params was undefined'}</Text>
    </View>
  );
}


const App: () => React$Node = () => {
  return (
    <>
     <NavigationNativeContainer>
      {MyTabs()}
      </NavigationNativeContainer>
    </>
  );
};

export default App;`

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator

**Comment by thijs-qv** [comment]
My bad, thanks for your help!
