### ISSUE TITLE
Question about using static navigationOptions

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/navigation-ex#311]
Can we still use it within a screen with v5?

**Comment by ctopher7** [comment]
you can use props.navigation.setOptions() to replace that. if you still want to use it, use functional components

example:
```
const Main = (props)=>{return <View/>}
Main.navigationOptions = ({navigation})=>({header:'MainScreen'})
export default Main
```

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/upgrading-from-4.x.html
