### ISSUE TITLE
gestureEnabled in native-stack does not have any effect

### ISSUE THREAD

**Issue by bisak** [react-navigation/navigation-ex#315]
```
const defaultScreenOptions = {
    headerShown: false,
    contentStyle: {
        backgroundColor: '#000',
    },
    gestureEnabled: false,
};

const StackNav = () => {
    return (
        <Stack.Navigator screenOptions={defaultScreenOptions}>
            <Stack.Screen name="A" component={A} />
            <Stack.Screen name="B" component={B} />
            <Stack.Screen name="C" component={C} />
        </Stack.Navigator>
    );
};
```
The Stack is nested in a Tab
With `gestureEnabled: false` i'm still able to swipe right on iPhone and go back a screen.
#228 related, but kind of irrelevant

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.0.0-alpha.29
| @react-navigation/native-stack | 5.0.0-alpha.29
| react-native-screens           | 2.0.0-alpha.32
| react-native                   | 0.61.5

**Comment by Jalson1982** [comment]
In stack screen add options and there put gestureEnabled: false. Like this :
<Stack.Screen name="A" component={A} options={{gestureEnabled: false}} />

**Comment by bisak** [comment]
I've literally tried putting it everywhere, on every single route, navigator, component and whatever, with no success.

**Comment by troublediehard** [comment]
same for me
```
                <Stack.Screen
                  name={routes.NAVIGATION_CATEGORIES}
                  component={CategoriesScreen}
                  options={{
                    title: localizationContext.t('categories screen title'),
                    headerBackTitleVisible: false,
                    gestureEnabled: true,
                  }}
                />
```

**Comment by Jalson1982** [comment]
Yes with native stack no effect. I tried also gestureResponseDistance: {horizontal: 100} no effect at all :(

**Comment by satya164** [comment]
react native screens was recently released with a breaking change where the property was moved. we need to update our code to pass it to the updated component.

**Comment by Jalson1982** [comment]
@satya164 is there any time frame for this to update :)

**Comment by satya164** [comment]
After they release a new version with correct type definitions. Currently it had wrong type definitions which will give error on usage.

**Comment by Jalson1982** [comment]
Ok cool. Is this fixed yesterday by you? https://github.com/kmagiera/react-native-screens/commit/eb2a1ae8fd622eeafdfc31be041878b181cb77d8

**Comment by satya164** [comment]
Yes but it's not published to npm

**Comment by Jalson1982** [comment]
Ah ok cool. So will we have option to update also gestureResponseDistance as it is not available right now?

**Comment by satya164** [comment]
No that's not an option in screens. If you want more control, you'll need to open an issue is screens repo. native stack is a small wrapper over screens.

**Comment by Jalson1982** [comment]
Do you maybe know how to disable with native screens then to open drawer menu on swipe righ? With normal stack navigator if you swipe right it will not open drawer on native stack it opens drawer.
