### ISSUE TITLE
useLinking doesn't work on [Android]

### ISSUE THREAD

**Issue by bsonmez** [react-navigation/navigation-ex#320]
Hello!

On android, userLinking does not work at all. And also the issue is I can't catch any on the console as well.

However, it works on iOS the way expected. 

```
const [initialState, setInitialState] = useState();
  const [isReady, setIsReady] = useState();

  const { getInitialState } = useLinking(ref, {
    prefixes: ["xxx://"],
    config: {
      Auth: {
        Login: "Login",
      }
    }
  });

  useEffect(() => {
    getInitialState()
      .catch(e => {
        console.log(e);
      })
      .then(state => {
        console.log("INITIALSTATE", state);
        if (state !== undefined) {
          setInitialState(state);
        }
        setIsReady(true);
      });
  }, [getInitialState]);
```

    "@react-navigation/bottom-tabs": "^5.0.0-alpha.28",
    "@react-navigation/native": "^5.0.0-alpha.21",
    "@react-navigation/native-stack": "^5.0.0-alpha.19",
    "@react-navigation/stack": "^5.0.0-alpha.37",
    "react-native": "0.61.5",

**Comment by satya164** [comment]
What does `Linking.getInitialUrl()` give you?

**Comment by bsonmez** [comment]
> What does `Linking.getInitialUrl()` give you?

It gives:

`Promise {_40: 0, _65: 0, _55: null, _72: null}`

**Comment by bsonmez** [comment]
@satya164 I start checking deeply and I guess the issue raises after second console log. console.log(3) it does not appear at all. So checked it on react-native, so far, this is what I have 
[found about the error.](https://github.com/facebook/react-native/issues/26947) 

```
const getInitialState = React.useCallback(async () => {
    console.log('1')
    console.log("2")

    const url = await Linking.getInitialURL();
    console.log("3")
    const path = url ? extractPathFromURL(url) : null;
    console.log("4")

    if (path) {
      return getStateFromPathRef.current(path, configRef.current);
    } else {
      return undefined;
    }
  }, [extractPathFromURL]);
```

**Comment by satya164** [comment]
So it seems to be a bug in React Native. Closing since we can't do much about it. Please follow the issue on the React Native repo.
