### ISSUE TITLE
SyntaxError  in @react-navigation/routers/src/TabRouter.tsx

### ISSUE THREAD

**Issue by hadnet** [react-navigation/navigation-ex#351]
Using @react-navigation/native 5.0.0-alpha.35 and Expo SDK 36.0.0 and expo 3.11.9

SyntaxError: /Users/jon/ReactNativeProjects/MyApp/node_modules/@react-navigation/routers/src/TabRouter.tsx: Unexpected token (36:30)

  34 | };
  35 | 
> 36 | const TYPE_ROUTE = 'route' as const;
     |                               ^
  37 | 
  38 | export const TabActions = {
  39 |   jumpTo(name: string, params?: object): TabActionType {
Failed building JavaScript bundle.

But when I delete this "as const" everything is working ok.

**Comment by satya164** [comment]
Delete your `yarn.lock`/`package-lock.json` and run `yarn`/`npm install`
