### ISSUE TITLE
Hidden header becomes visible when going back from screen with header: null

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/navigation-ex#65]
<img width="496" alt="Screen Shot 2019-08-22 at 10 41 46" src="https://user-images.githubusercontent.com/90494/63540604-36510880-c4d1-11e9-9077-789bbdfe2d04.png">

**Comment by osdnk** [comment]
fixed 🌮 
https://github.com/react-navigation/navigation-ex/commit/469ec31cc571c02d5831b118dab2bf247d7f1832
