### ISSUE TITLE
Animation issue when using `TransitionPresets.ModalSlideFromBottomIOS` with card stack

### ISSUE THREAD

**Issue by janicduplessis** [react-navigation/navigation-ex#87]
I have a card stack with the default transition preset on iOS. When I push a second screen on it with `TransitionPresets.ModalSlideFromBottomIOS` it causes this animation issue.

![navigationbug](https://user-images.githubusercontent.com/2677334/64054634-faafe180-cb55-11e9-8b96-74b96fd07a2d.gif)

Something like this should repro

```js
<RootStack.Navigator
  initialRouteName="a"
  mode="card"
>
  <RootStack.screen name="a" />
  <RootStack.screen name="b" options={{...TransitionPresets.ModalSlideFromBottomIOS}} />
</RootStack.Navigator>

...

navigate('b')
```

**Comment by satya164** [comment]
This is a result of screen controlling its own animations. Perhaps it'll be better if the focused screen controlled it's own as well as previous screen's animations,

**Comment by janicduplessis** [comment]
If we can have the preset also control the previous screen I think it would be great. Not sure if we'll hit some edge cases but this would be better than now.

**Comment by satya164** [comment]
It won't work properly unless the idle state of both presets (preset if current screen and previous screen) are the same. For example, modal's idle state has a top margin and border radius etc. When we switch the preset it'll suddenly change the style to something else (the idle state of new preset which will be different).

This means we can't safely apply current screen's preset to previous screen and have it look good.

Fortunately the idle state of most built in presets are same except the modal. So we could provide a preset which combines both. But it'll still need some code like above to work.

**Comment by leethree** [comment]
I'm seeing the same problem. I think transition should be defined as a thing that is shared by two screens. The exit animation of a screen should be decided by the next screen instead by itself. 

This should be the default behaviour without any custom interpolator:
e.g.
0. Screen A has default transition presets. Screen B has "modal" transition presets.
1. On screen A, `navigate('B')`
2. Screen A should not move while screen B slides in from bottom.
3. On screen B, `goBack()`
4. Screen B slides down and reveals screen A.

![Kapture 2019-09-13 at 11 48 57](https://user-images.githubusercontent.com/648142/64857462-8462b300-d61c-11e9-91a2-dc821638928c.gif)

**Comment by satya164** [comment]
> This means we can't safely apply current screen's preset to previous screen and have it look good.

**Comment by leethree** [comment]
I'm not saying we should "apply current screen's preset to previous screen". I'm saying that the current screen preset should specify what the previous screen should do, which is a different thing from the idle state of the current screen.

**Comment by satya164** [comment]
I don't think there's any difference in what you're saying.

**Comment by satya164** [comment]
We'll probably end up doing that anyway and it'll work in many cases, but in some cases it'll break without manual work (such as combining slide and modal presentation animation)

**Comment by leethree** [comment]
For the iOS 13 card style, it probably makes more sense for it to be a different navigator, e.g. `card-stack`. It's similar to `material-bottom-tabs` vs `bottom-tabs`. For all other use cases, we should assume that all idle states are the same. Then there wouldn't be a problem with preset controlling the previous screen animation.
