### ISSUE TITLE
Being able to specify a stacks route from another stack

### ISSUE THREAD

**Issue by kennetpostigo** [react-navigation/navigation-ex#90]
I ran into an issue where I have a root stack, and two children stacks as part of this parent stack. When I'm in one of the children stack and want to navigate to another children stack, but a specific screen of that other children stack i'm currently unable to unless I dynamically set the `initialRouteName`. However this seems like an odd way to do that.

I wish that I could do something like:
```js
navigate.push("Auth/Login");
```

The other childrens stack is named `Auth` and it's child screen is called `Login`. So in this case i'm saying go to this stack called `Auth` but specifically render the `Login` screen in that stack.

@satya164

**Comment by satya164** [comment]
We wouldn't support the exact API coz it won't be possible to type-check it, but we could do something like this:

```js
navigation.push('Auth', { name: 'Login', params: { ... } })
```

It should be easy to implement. Under the hood we can just pass the `name` as `initialRouteName` and `params` as `initialParams`.

**Comment by osdnk** [comment]
maybe ```navigate.push[{ name: "Auth" }, { name: "Login" }])```

**Comment by satya164** [comment]
@osdnk I'm not suggesting to actually change the signature of `push` here. Just saying that internally we take the `params` for the screen containing the navigator which will be `{ name: 'Login', params: { ... } }` and determine `initialRouteName` and `initialParams` for that route based on it. This means it'll automatically work for other actions too, such as `navigate`.

If the navigator is already rendered, we can take this and dispatch a `navigate` action as well to switch to that screen.

**Comment by davidgovea** [comment]
This will be great! In the previous version, I achieved this with 'compound' navigation actions (containing nested actions)
