### ISSUE TITLE
Previous Stack Header doesn't go away

### ISSUE THREAD

**Issue by kennetpostigo** [react-navigation/navigation-ex#92]
I recently noticed that sometimes stack headers don't go away, the previous stack header remains behind the current/new one, you can see it because they have different background colors and heights.

![image](https://user-images.githubusercontent.com/8888991/64080598-42ed1200-ccc4-11e9-900d-dd5f51721ccd.png)

**Comment by brentvatne** [comment]
@kennetpostigo - can you provide a reproducible example?

**Comment by satya164** [comment]
This was because the header was custom with `headerMode: 'screen'` and didn't handle the animations. Closing.
