### ISSUE TITLE
Header Remains visible after popping

### ISSUE THREAD

**Issue by kennetpostigo** [react-navigation/navigation-ex#93]
When popping back to previous screen the current header will remain visible for a few seconds despite the screen changing back to the previous page. I notice this specifically when not using the default header

**Comment by satya164** [comment]
Are you using `headerMode: 'screen'` or `'float'`? If `'float'`, do you handle the animation of the header?

**Comment by kennetpostigo** [comment]
I haven't configured that, so whatever the default is

**Comment by satya164** [comment]
Can the try setting it to `screen`?

**Comment by kennetpostigo** [comment]
@satya164 I get the same behavior
