### ISSUE TITLE
Custom contentComponent in Drawer re-render everytime

### ISSUE THREAD

**Issue by alexakasanjeev** [react-navigation/navigation-ex#99]
### Current Behavior

I have implemented a **Drawer** which host a **Stack** navigator inside. I am giving a custom component to be render in `contentComponent` in Drawer. But the custom component in Drawer keeps rendering after every:
1. Whenever the Drawer is open
2. Whenever the Drawer is close
3. Any screen is open in Stack Navigator

### Expected Behavior

- custom component given to Drawer should not keep re rendering every time any screen is open from the stack

### How to reproduce

1. run `git clone https://github.com/alexakasanjeev/magento_react_native.git && cd magento_react_native`
2. install dependency `npm install`
3. Change the branch to `git checkout feature/react-navigation`
4. In terminal type `npm start`
5. In another terminal run `react-native run-android`
6. Once the app is running in device, enable `Debug Js Remotely` from dev menu
7. Open the console of chrome and click on any button in the App
8. Every time any button is clicked to open new screen, the custom component keeps re-rendering as seen from console logs
>  Rendering Drawer Navigation!

#### Screenshots
![Screenshot from 2019-09-14 16-26-43](https://user-images.githubusercontent.com/13250741/64907156-8d32b200-d70c-11e9-98fc-be102aa36f67.png)

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | ^5.0.0-alpha.8
| @react-navigation/native | ^5.0.0-alpha.7
| @react-navigation/drawer | ^5.0.0-alpha.8
| @react-navigation/stack | ^5.0.0-alpha.15
| react-native     | 0.60.4
| node             | v10.15.3
| yarn      | 1.17.3

**Comment by satya164** [comment]
What is the problem with re rendering?

**Comment by alexakasanjeev** [comment]
Hi @satya164, If the component re render everytime even if it is not used, it is waste of render and potential slow down for the APP.

Explain me this,

Consider I have three Screen 
1. `Home` that shows humburger icon to toggle drawer on the side on toolbar
2. `Home` has a button to go to `Screen A`
3. `ScreenA` has a button to go to `ScreenB`

Now I 'm on a `ScreenA` and in place of humburger icon satck navigator shows back button, which is correct, now I go to `ScreenB` from `ScreenA`, even doing that, drawer re-renders, can you tell me what was the use of drawer from going to ScreenB to ScreenA, why it keeps re-rendering

You can clone the project and see for yourself

**Comment by alexakasanjeev** [comment]
Also as `Home` (the root screen) is render only once, doesn't matter how many screen you open in stack or press back button, same functionality should be of Drawer

**Comment by satya164** [comment]
> If the component re render everytime even if it is not used, it is waste of render and potential slow down for the APP.

The premise of React is that you let React optimize updates for you so you don't have to think about re-renders.

Is it actually causing any slow down in your app? If it is causing a slow down and your custom component is heavy, you can optimize your component with `PureComponent`/`React.memo` manually.

> why it keeps re-rendering

Because navigation state is nested. Changing child state changes state of parent.

**Comment by alexakasanjeev** [comment]
Bro I have used `PureComponent`, it's not working

this is the same issue as

**Comment by satya164** [comment]
That's a completely different report regarding unmounting on navigating away.

> Bro I have used PureComponent, it's not working

You can't just put `PureComponent` on the custom component and expect it to work. It is re-rendering because its props are changing. Pure component won't prevent that. If we could automatically prevent the re-render, we would.

You'll need to extract expensive parts out to separate component, pass the minimum required data as props to it, and then apply `React.memo`/`PureComponent`.

**Comment by alexakasanjeev** [comment]
Can you atleast look once in my code, there is nothing expensive, i have created dummy views, they just contain a button to navigate to different screen, there is no business logic in it, Even the custom, drawer component just has a button to close the drawer

**Comment by satya164** [comment]
As I mentioned, the child navigation state changes which causes parent state to change. Re-rendering the component is expected behaviour and not a bug.

If the view is simple, why do you care about re-rendering? If there's nothing expensive then you don't need to prevent re-render. Is it actually causing performance issues for you?

**Comment by alexakasanjeev** [comment]
Bro this is my actual screen
![1](https://user-images.githubusercontent.com/13250741/64907938-f8818180-d716-11e9-8a18-16478d47c4d3.png)


**Drawer screen**
![2](https://user-images.githubusercontent.com/13250741/64907955-2e266a80-d717-11e9-8363-9c3108116c97.png)

now the custom drawer component keeps re-rendering even if I don't click anything, and no state or no async operation is happening, nothing, and the drawer component re renders in react-navigation@4.x which is making my app slow

to prevent that i'm trying react navigation@5.x  so that once drawer component loads it doesn't re-render on its own

**Comment by alexakasanjeev** [comment]
Please atleast once, please just clone the repo, change it to branch `feature/react-navigation` and install dependency and just see for yourself, I may not be able to explain you the issue but please just run the code, and then tell me if it's a bug or not

**Comment by satya164** [comment]
If your drawer is expensive to re-render, extract the expensive parts to separate component and apply pure component.

```js
class MyCustomComponent extends PureComponent {
  // ... your expensive component
}


const ContentComponent = ({ navigation }) => {
  // Don't pass all the props so we don't trigger re-render
  // Only pass required props
  return <MyCustomComponent navigation={navigation} />
}

// ...

<Drawer.Navigator contentComponent={ContentComponent} />
```

React Navigation cannot optimize your component. Only you know what props can safely trigger a re-render and what props cannot in your custom component.

**Comment by satya164** [comment]
> Please atleast once, please just clone the repo, change it to branch feature/react-navigation and install dependency and just see for yourself, I may not be able to explain you the issue but please just run the code, and then tell me if it's a bug or not

Dude, I already told you its expected behaviour. I won't find something new by running your code. I already know that the custom component will re-render.

If re-render is expensive in your case, you need optimize your custom component manually. React Navigation cannot prevent re-render automatically for the reason I mentioned.

**Comment by alexakasanjeev** [comment]
bro this is my custom component, which keeps re-rendering, could you tell me which part should I extract it out 

```js
const DrawerPage = () => {
    console.log('Rendering Drawer Navigation!');
    return (
      <View>
        <Text>DrawerPage</Text>
        <Button
          title="Close Drawer"
          onPress={() => this.props.navigation.toggleDrawer()}
        />
      </View>
    );
}
```

Should I put `console.log` in Pure component or should I return` <><./>` in my custom component, what do you think is complex in above code

**Comment by satya164** [comment]
See my code https://github.com/react-navigation/navigation-ex/issues/99#issuecomment-531475410

**Comment by alexakasanjeev** [comment]
I did that, now only `ContentComponent` is rendering, `MyCustomComponent` is not re-rendering every time 

Thank you so much for your help and your patience, and I'm really sorry If I came out rude
